server:
 port: 8765

spring:
  application:
    name: APIGateway
  

  cloud:
   discovery:
    enabled: true
 
   gateway:
      routes:
      - id: CartService
        uri: http://20.127.159.231:9300/cart/
        predicates:
        - Path=/cart/**
      - id: PromotionAndDiscountService
        uri: http://172.203.170.91:9400/discount/
        predicates:
        - Path=/discount/**
      - id: PromotionAndDiscountService
        uri: http://172.203.170.91:9400/promotion/
        predicates:
        - Path=/promotion/**
     
        
      - id: ProductService
        uri: http://localhost:9030/api/products/ 
        predicates:
         - Path=/api/products/**

eureka:
  client:
    service-url:
     defaultZone: http://20.127.159.231:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
   hostname: 20.127.159.231
   ip-address: 20.127.159.231
   preferIpAddress: true
   
      
